[
  {
    name: "Redmi 5x android 4k TV",
    variant: "45 inches",
    brand: "redmi",
    category: "electronics",
    sub: "TV",
    description:
      "Redmi 108 cm (43 inches) Full HD Smart LED TV | L43M6-RA (Black) (2021 Model) | With Android 11",
    rating: "4.5",
    isOffer: false,
    originalPrice: "32000",
    exchangable: true,
    about: [
      "Resolution : Full HD (1920x1080) resolution | Refresh Rate : 60 Hertz | 178 Degree wide viewing angle",
      "Connectivity: 2 HDMI ports to connect set top box, Blu-Ray players, gaming console | 2 USB ports to connect hard drives and other USB devices | 3.5mm to connect your headphones | Bluetooth 5.0 to connect Bluetooth speakers, earphones and TWS earphones",
      "Sound: 20 Watts Powerful Stereo Speakers | Dolby Audio | DTS Virtual: X and DTS-HD | Dolby Atmos pass through ARC port",
      "Smart TV Features : Android TV 11 | Chromecast built-in | PatchWall 4 with IMDb integration | Kids Mode with Parental Lock | 75+ Free Live Channels | Universal search | Language Universe (16+ Languages) | India's Top 10 | Miracast | Supported Apps: Prime Video | Netflix | Disney + Hotstar | YouTube | Apple TV | 5000+ apps from Play Store | Auto Low Latency Mode | Quad core processor | Dual band Wi-Fi | 1GB RAM + 8GB Storage",
      "Display: A+ Grade LED panel | Vivid Picture Engine | Detailed Picture Controls | Ultra bright screen | Dynamic contrast | Dynamic backlight",
    ],
    images: [
      "/electronics/TV/redmi1.jpg",
      "/electronics/TV/redmi2.jpg",
      "/electronics/TV/redmi3.jpg",
      "/electronics/TV/redmi4.jpg",
      "/electronics/TV/redmi5.jpg",
    ],
  },
  {
    name: "Samsung 32 inch TV",
    variant: "32 inches",
    brand: "samsung",
    category: "electronics",
    sub: "TV",
    description:
      "Samsung 80 cm (32 inches) Wondertainment Series HD Ready LED Smart TV UA32TE40AAKBXL (Titan Gray) (2020 Model)",
    rating: "4",
    isOffer: false,
    originalPrice: "18000",
    exchangable: true,
    about: [
      "Resolution: HD Ready (1366x768) | Refresh Rate: 60 hertz",
      "Connectivity: 2 HDMI ports to connect set top box, Blu Ray players, gaming console | 1 USB ports to connect hard drives and other USB devices",
      "Smart TV Features : Voice Assistants | SmartThings App | Personal Computer | Home Cloud | Live Cast | Screen Share | Music System |Alexa Built-in: Voice control your TV and your day. Just ask Alexa to search for movies, play music, control smart home devices, get sports updates and more",
      "Sound : 20 Watts Output | Dolby Digital Plus",
      "Display : LED Panel | Mega Contrast | PurColor | HD Picture Quality | Slim & Stylish Design",
    ],
    images: [
      "/electronics/TV/samsung1.jpg",
      "/electronics/TV/samsung2.jpg",
      "/electronics/TV/samsung3.jpg",
      "/electronics/TV/samsung4.jpg",
      "/electronics/TV/samsung5.jpg",
    ],
  },
  {
    name: "Sony Bravia 65 inch TV",
    variant: "65 inches",
    brand: "sony",
    category: "electronics",
    sub: "TV",
    description:
      "Sony Bravia 164 cm (65 inches) 4K Ultra HD Smart LED Google TV KD-65X80AJ (Black) (2021 Model) | with Alexa Compatibility",
    rating: "4.5",
    isOffer: false,
    originalPrice: "100000",
    exchangable: true,
    about: [
      "Resolution: 4K Ultra HD (3840 x 2160) | Refresh Rate: 60 hertz",
      "Connectivity: 4 HDMI ports to connect set top box, Blu Ray players, gaming console | 2 USB ports to connect hard drives and other USB devices",
      "Smart TV Features: Google TV | Voice Search | Google Play | Chromecast | Netflix | Amazon Prime Video | HDR Gaming | Additional Features: Apple Airplay | Apple Homekit |Alexa",
      "Sound : 20 Watts Output | X-Balanced Speaker| Bass Reflex speakers | Dolby Atmos | Ambient Optimization",
      "Display: X1 | 4K HDR | Triluminos pro Display | 4K X-Reality Pro | Motionflow XR100",
    ],
    images: [
      "/electronics/TV/sony1.jpg",
      "/electronics/TV/sony2.jpg",
      "/electronics/TV/sony3.jpg",
      "/electronics/TV/sony4.jpg",
      "/electronics/TV/sony5.jpg",
    ],
  },
];
